# Generated by Django 4.2.4 on 2023-10-01 08:20

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_customuser_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="profile_pics",
                validators=[utils.validators.validate_file_size],
                verbose_name="تصویر پروفایل",
            ),
        ),
    ]
