# Generated by Django 4.2.4 on 2023-09-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0003_alter_taskassignee_task_alter_workspace_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="workspace",
            name="thumbnail_alt",
        ),
        migrations.AddField(
            model_name="workspace",
            name="color",
            field=models.CharField(
                default="#000", max_length=256, verbose_name="Color"
            ),
        ),
    ]
