# Generated by Django 4.2.4 on 2023-09-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0007_alter_board_name_alter_board_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "old_priority",
                    models.IntegerField(default=0, verbose_name="Old Priority"),
                ),
                (
                    "new_priority",
                    models.IntegerField(default=0, verbose_name="New Priority"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.task",
                        verbose_name="Task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Log",
                "verbose_name_plural": "Task Logs",
            },
        ),
    ]
