name: Trello
on:
  push:
    branches:
      - main
      - develop
      - release
  pull_request:
    branches:
      - main
      - develop
      - release
      - refactor_v2

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install flake8

      - name: Run flake8
        run: make lint